# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WerckerModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TokeName', models.CharField(max_length=20)),
                ('Token', models.CharField(max_length=200)),
            ],
        ),
    ]
